# Generated by Django 5.0.2 on 2024-08-27 22:36

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Enter a unique name.', max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters'), projects.models.validate_unique_project_name]),
        ),
    ]
