# Generated by Django 5.0.7 on 2024-08-27 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters'), django.core.validators.RegexValidator('^[a-zA-Z0-9_-]*$', message='Name must be only alphanumeric characters, underscores, and hypens are allowed')]),
        ),
    ]
