# Generated by Django 5.0.2 on 2024-08-27 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0002_alter_featureflag_name'),
        ('projects', '0003_alter_project_description_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description.'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(help_text='Enter a unique name.', max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters'), django.core.validators.RegexValidator('^[a-zA-Z0-9_-]*$', message='Name must be only alphanumeric characters, underscores, and hypens.')]),
        ),
        migrations.AlterUniqueTogether(
            name='featureflag',
            unique_together={('project', 'name')},
        ),
    ]
