# Generated by Django 5.0.7 on 2024-08-24 23:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environment')),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_flags.featureflag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
